// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: calculator.proto
// Protobuf C++ Version: 5.29.3

#include "calculator.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace calculator {

inline constexpr ArithmeticResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : result_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ArithmeticResponse::ArithmeticResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ArithmeticResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ArithmeticResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ArithmeticResponseDefaultTypeInternal() {}
  union {
    ArithmeticResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ArithmeticResponseDefaultTypeInternal _ArithmeticResponse_default_instance_;

inline constexpr ArithmeticRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : a_{0},
        b_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ArithmeticRequest::ArithmeticRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ArithmeticRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ArithmeticRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ArithmeticRequestDefaultTypeInternal() {}
  union {
    ArithmeticRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ArithmeticRequestDefaultTypeInternal _ArithmeticRequest_default_instance_;
}  // namespace calculator
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_calculator_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_calculator_2eproto = nullptr;
const ::uint32_t
    TableStruct_calculator_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::calculator::ArithmeticRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::calculator::ArithmeticRequest, _impl_.a_),
        PROTOBUF_FIELD_OFFSET(::calculator::ArithmeticRequest, _impl_.b_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::calculator::ArithmeticResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::calculator::ArithmeticResponse, _impl_.result_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::calculator::ArithmeticRequest)},
        {10, -1, -1, sizeof(::calculator::ArithmeticResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::calculator::_ArithmeticRequest_default_instance_._instance,
    &::calculator::_ArithmeticResponse_default_instance_._instance,
};
const char descriptor_table_protodef_calculator_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020calculator.proto\022\ncalculator\")\n\021Arithm"
    "eticRequest\022\t\n\001a\030\001 \001(\005\022\t\n\001b\030\002 \001(\005\"$\n\022Ari"
    "thmeticResponse\022\016\n\006result\030\001 \001(\0052\261\002\n\nCalc"
    "ulator\022D\n\003Add\022\035.calculator.ArithmeticReq"
    "uest\032\036.calculator.ArithmeticResponse\022I\n\010"
    "Multiply\022\035.calculator.ArithmeticRequest\032"
    "\036.calculator.ArithmeticResponse\022I\n\010Subtr"
    "act\022\035.calculator.ArithmeticRequest\032\036.cal"
    "culator.ArithmeticResponse\022G\n\006Divide\022\035.c"
    "alculator.ArithmeticRequest\032\036.calculator"
    ".ArithmeticResponseb\006proto3"
};
static ::absl::once_flag descriptor_table_calculator_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_calculator_2eproto = {
    false,
    false,
    427,
    descriptor_table_protodef_calculator_2eproto,
    "calculator.proto",
    &descriptor_table_calculator_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_calculator_2eproto::offsets,
    file_level_enum_descriptors_calculator_2eproto,
    file_level_service_descriptors_calculator_2eproto,
};
namespace calculator {
// ===================================================================

class ArithmeticRequest::_Internal {
 public:
};

ArithmeticRequest::ArithmeticRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:calculator.ArithmeticRequest)
}
ArithmeticRequest::ArithmeticRequest(
    ::google::protobuf::Arena* arena, const ArithmeticRequest& from)
    : ArithmeticRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ArithmeticRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ArithmeticRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, a_),
           0,
           offsetof(Impl_, b_) -
               offsetof(Impl_, a_) +
               sizeof(Impl_::b_));
}
ArithmeticRequest::~ArithmeticRequest() {
  // @@protoc_insertion_point(destructor:calculator.ArithmeticRequest)
  SharedDtor(*this);
}
inline void ArithmeticRequest::SharedDtor(MessageLite& self) {
  ArithmeticRequest& this_ = static_cast<ArithmeticRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ArithmeticRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ArithmeticRequest(arena);
}
constexpr auto ArithmeticRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ArithmeticRequest),
                                            alignof(ArithmeticRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ArithmeticRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ArithmeticRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ArithmeticRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ArithmeticRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ArithmeticRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ArithmeticRequest>(), &ArithmeticRequest::ByteSizeLong,
            &ArithmeticRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ArithmeticRequest, _impl_._cached_size_),
        false,
    },
    &ArithmeticRequest::kDescriptorMethods,
    &descriptor_table_calculator_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ArithmeticRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> ArithmeticRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::calculator::ArithmeticRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 b = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ArithmeticRequest, _impl_.b_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ArithmeticRequest, _impl_.b_)}},
    // int32 a = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ArithmeticRequest, _impl_.a_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ArithmeticRequest, _impl_.a_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 a = 1;
    {PROTOBUF_FIELD_OFFSET(ArithmeticRequest, _impl_.a_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 b = 2;
    {PROTOBUF_FIELD_OFFSET(ArithmeticRequest, _impl_.b_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ArithmeticRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:calculator.ArithmeticRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.a_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.b_) -
      reinterpret_cast<char*>(&_impl_.a_)) + sizeof(_impl_.b_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ArithmeticRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ArithmeticRequest& this_ = static_cast<const ArithmeticRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ArithmeticRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ArithmeticRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:calculator.ArithmeticRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 a = 1;
          if (this_._internal_a() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_a(), target);
          }

          // int32 b = 2;
          if (this_._internal_b() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_b(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:calculator.ArithmeticRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ArithmeticRequest::ByteSizeLong(const MessageLite& base) {
          const ArithmeticRequest& this_ = static_cast<const ArithmeticRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ArithmeticRequest::ByteSizeLong() const {
          const ArithmeticRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:calculator.ArithmeticRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 a = 1;
            if (this_._internal_a() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_a());
            }
            // int32 b = 2;
            if (this_._internal_b() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_b());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ArithmeticRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ArithmeticRequest*>(&to_msg);
  auto& from = static_cast<const ArithmeticRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:calculator.ArithmeticRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_a() != 0) {
    _this->_impl_.a_ = from._impl_.a_;
  }
  if (from._internal_b() != 0) {
    _this->_impl_.b_ = from._impl_.b_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ArithmeticRequest::CopyFrom(const ArithmeticRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:calculator.ArithmeticRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ArithmeticRequest::InternalSwap(ArithmeticRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ArithmeticRequest, _impl_.b_)
      + sizeof(ArithmeticRequest::_impl_.b_)
      - PROTOBUF_FIELD_OFFSET(ArithmeticRequest, _impl_.a_)>(
          reinterpret_cast<char*>(&_impl_.a_),
          reinterpret_cast<char*>(&other->_impl_.a_));
}

::google::protobuf::Metadata ArithmeticRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ArithmeticResponse::_Internal {
 public:
};

ArithmeticResponse::ArithmeticResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:calculator.ArithmeticResponse)
}
ArithmeticResponse::ArithmeticResponse(
    ::google::protobuf::Arena* arena, const ArithmeticResponse& from)
    : ArithmeticResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ArithmeticResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ArithmeticResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.result_ = {};
}
ArithmeticResponse::~ArithmeticResponse() {
  // @@protoc_insertion_point(destructor:calculator.ArithmeticResponse)
  SharedDtor(*this);
}
inline void ArithmeticResponse::SharedDtor(MessageLite& self) {
  ArithmeticResponse& this_ = static_cast<ArithmeticResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ArithmeticResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ArithmeticResponse(arena);
}
constexpr auto ArithmeticResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ArithmeticResponse),
                                            alignof(ArithmeticResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ArithmeticResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ArithmeticResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ArithmeticResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ArithmeticResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ArithmeticResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ArithmeticResponse>(), &ArithmeticResponse::ByteSizeLong,
            &ArithmeticResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ArithmeticResponse, _impl_._cached_size_),
        false,
    },
    &ArithmeticResponse::kDescriptorMethods,
    &descriptor_table_calculator_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ArithmeticResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ArithmeticResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::calculator::ArithmeticResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 result = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ArithmeticResponse, _impl_.result_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ArithmeticResponse, _impl_.result_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 result = 1;
    {PROTOBUF_FIELD_OFFSET(ArithmeticResponse, _impl_.result_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ArithmeticResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:calculator.ArithmeticResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ArithmeticResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ArithmeticResponse& this_ = static_cast<const ArithmeticResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ArithmeticResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ArithmeticResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:calculator.ArithmeticResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 result = 1;
          if (this_._internal_result() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_result(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:calculator.ArithmeticResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ArithmeticResponse::ByteSizeLong(const MessageLite& base) {
          const ArithmeticResponse& this_ = static_cast<const ArithmeticResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ArithmeticResponse::ByteSizeLong() const {
          const ArithmeticResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:calculator.ArithmeticResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 result = 1;
            if (this_._internal_result() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_result());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ArithmeticResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ArithmeticResponse*>(&to_msg);
  auto& from = static_cast<const ArithmeticResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:calculator.ArithmeticResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_result() != 0) {
    _this->_impl_.result_ = from._impl_.result_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ArithmeticResponse::CopyFrom(const ArithmeticResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:calculator.ArithmeticResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ArithmeticResponse::InternalSwap(ArithmeticResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.result_, other->_impl_.result_);
}

::google::protobuf::Metadata ArithmeticResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace calculator
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_calculator_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
